export const MaterialTypes = [
  { value: 'tuberia_pvc', label: 'Tubería PVC' },
  { value: 'tuberia_cobre', label: 'Tubería de cobre' },
  { value: 'tuberia_multicapa', label: 'Tubería multicapa' },
  { value: 'tuberia_pex', label: 'Tubería PEX' },
  { value: 'codo', label: 'Codo (45º / 90º)' },
  { value: 'manguito', label: 'Manguito' },
  { value: 'te', label: 'T (Derivación)' },
  { value: 'reduccion', label: 'Reducción' },
  { value: 'union', label: 'Unión / Enlace' },
  { value: 'valvula_esfera', label: 'Válvula de esfera' },
  { value: 'valvula_corte', label: 'Válvula de corte' },
  { value: 'valvula_antirretorno', label: 'Válvula antirretorno' },
  { value: 'sifon', label: 'Sifón' },
  { value: 'desague', label: 'Accesorios de desagüe' },
  { value: 'latiguillo', label: 'Latiguillo' },
  { value: 'llave_escuadra', label: 'Llave de escuadra' },
  { value: 'grifo', label: 'Grifo' },
  { value: 'flexo_ducha', label: 'Flexo de ducha' },
  { value: 'cabezal_ducha', label: 'Cabezal de ducha' },
  { value: 'teflon', label: 'Teflón' },
  { value: 'silicona', label: 'Silicona sanitaria' },
  { value: 'pegamento_pvc', label: 'Pegamento PVC' },
  { value: 'radiador', label: 'Radiador' },
  { value: 'purgador', label: 'Purgador' },
  { value: 'colector', label: 'Colector calefacción' },
  { value: 'junta_goma', label: 'Junta de goma' },
  { value: 'filtro', label: 'Filtro' },
  { value: 'otro', label: 'Otro' },
];
